### ISSUE TITLE
Hash/MultiValue is required module?

### ISSUE THREAD

**Issue by yuji** [movabletype/mt-plugin-google-openid-connect#1]
Our QA team reports this error.

failed loading package GoogleOpenIDConnect::Auth::GoogleOIDC for routine GoogleOpenIDConnect::Auth::GoogleOIDC::condition: Can't locate Hash/MultiValue.pm in @INC (@INC contains:

**Comment by rmasco** [comment]
I rethink the module.
Please test again .
